version: 2
jobs:
  build:
    working_directory: ~/react-mybooks
    
  docker:
    - image: circleci/node:6.11.0

    steps:
      - checkout

    dependencies:
      override:
        - yarn

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      
    test:
      override:
        - yarn test
        - yarn coverage