version: 2
jobs:
  build:
    working_directory: ~/react-mybooks
    docker:
      - image: circleci/node:6.11.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
    test:
        docker:
        - image:  circleci/node:6.11.0
        steps:
            - checkout
            - run:
                name: test-and-coverage
                command: npm run coverage
            - store_artifacts:
                path: coverage
                prefix: coverage